import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./anims.css";
import Header from "@/components/layout/header/header";
import AppThemeProvider from "@/context/appThemeContext";
import InitColorSchemeScript from "@mui/material/InitColorSchemeScript"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: false }}>
          <AppThemeProvider>
            <InitColorSchemeScript attribute="class" />
            {/* <Header /> */}
            <main className="min-h-screen flex flex-col gap-20">
              {children}
            </main>
            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
              <div className="">asdf</div>
              <div className="">asdf</div>
              <div className="">asdf</div>
            </footer>
          </AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
